### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [handsomematt/OpenEmpires#3]
Hi @HandsomeMatt 

Why did you stop development on this application?

**Comment by handsomematt** [comment]
Age of Empires 2 HD edition was announced a month after.

**Comment by ghost** [comment]
@HandsomeMatt Lmao does not mean give up on something that has potential.

Ever think of making a console based game like Moon base so so everything is text based

**Comment by handsomematt** [comment]
I have other stuff to do, there is already another open source AOE2 project here https://github.com/SFTtech/openage

And that idea is completely unrelated and boring?

**Comment by ghost** [comment]
@HandsomeMatt Okay cool
